name: BrutalSeller
version: '${project.version}'
main: ru.baronessdev.personal.brutalseller.Main
api-version: 1.16
depend: [Vault]
authors: [tom8hawk]
website: baronessdev.ru

commands:
  bwseller:
    usage: /bwseller
  bw:
    usage: /bw
    default: op
    description: Admin commands
